name: Check Vortex

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-machete

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl

      - name: Run cargo build
        run: cargo build

      - name: Run cargo nextest
        run: cargo nextest run

      - name: Run cargo machete
        run: cargo machete

      - name: Check formatting
        run: cargo fmt --check

      - name: Run server and smtp-fuzz.pl in parallel
        run: |
          sudo target/debug/vortex-smtp-server &
          SERVER_PID=$!
          echo "Server running in background with PID $SERVER_PID"

          perl Copyleft/smtp-fuzz.pl 127.0.0.1 25 &
          FUZZ_PID=$!
          echo "smtp-fuzz.pl running in background with PID $FUZZ_PID"

          wait $FUZZ_PID
          echo "smtp-fuzz.pl has finished"
