name: Run smtp-fuzz and cargo run

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl

      - name: Run cargo build
        run: cargo build

      - name: Run server and smtp-fuzz.pl in parallel
        run: |
          sudo target/debug/vortex-smtp-server &
          SERVER_PID=$!
          echo "Server running in background with PID $SERVER_PID"

          perl Copyleft/smtp-fuzz.pl 127.0.0.1 25 &
          FUZZ_PID=$!
          echo "smtp-fuzz.pl running in background with PID $FUZZ_PID"

          wait $FUZZ_PID
          echo "smtp-fuzz.pl has finished"

          # Stop the server after smtp-fuzz.pl is done
          sudo kill $SERVER_PID
          wait $SERVER_PID
          echo "Server has finished"
